### ISSUE TITLE
[Bug]: Showing wrong path

### ISSUE THREAD

**Issue by SOSkr** [porifa/vscode-laraphense#29]
### Bug description

Bug description
Laravel Intelephense use the wrong path (wrong separator \\) when i click on the suggestion
even though the (ctrl+click) uses the correct (/)

![image](https://user-images.githubusercontent.com/1152045/215331631-1e99156c-6d66-4882-be05-7b562423f6aa.png)

Update: 
I am using docker inside my WSL
if I click on that path it creates it on my Windows C drive.

### Plugin version

v1.20.4

### Operating system

Debian WSL2

**Comment by AamirSohailKmAs** [comment]
@SOSkr thanks for reporting this issue, It'll be fixed in next release

**Comment by AamirSohailKmAs** [comment]
Fixed in v1.20.5(https://marketplace.visualstudio.com/items/Porifa.laravel-intelephense/changelog)
