### ISSUE TITLE
[Bug]: Curly braces completion not detected inside quotes

### ISSUE THREAD

**Issue by rahulhaque** [porifa/vscode-laraphense#34]
### Bug description

Curly braces spacer not working when used inside HTML tag. It doesn't even auto close the braces.

### Plugin version

0.0.1

### Operating system

Linux

### Steps to reproduce

For any blade file containing any HTML tags, for example -
```html
<label>*doesn't_work_here*</label>
<input name="name" value="*doesn't_work_here*" />
```

**Comment by AamirSohailKmAs** [comment]
Thanks for reporting an issue, Actually we have 2 different extensions,

[Laravel Intelephense](https://marketplace.visualstudio.com/items?itemName=Porifa.laravel-intelephense)

[Laraphense](https://marketplace.visualstudio.com/items?itemName=Porifa.laraphense)

If you install [Laravel Intelephense](https://marketplace.visualstudio.com/items?itemName=Porifa.laravel-intelephense) it will work perfectly fine, give it a try,

**Comment by rahulhaque** [comment]
@AamirSohailKmAs I am already using the extension you've mentioned. I am certain it it is not working the way it should be. Did you try to reproduce the error and didn't found any?

**Comment by AamirSohailKmAs** [comment]
> @AamirSohailKmAs I am already using the extension you've mentioned. I am certain it it is not working the way it should be. Did you try to reproduce the error and didn't found any?

@rahulhaque Yes, I try to reproduce the error, and It is working well, This feature was removed from Laraphense, But it is still present and working in **Laravel Intelephense**
