### ISSUE TITLE
[Feature Request]: auth()->user()->can('gate') error

### ISSUE THREAD

**Issue by AMoktar** [porifa/vscode-laraphense#56]
### Feature Description
`[Feature Request]: auth()->user()->can('gate')` 

getting error : `Undefined method 'can'.intelephense(1013)`

Thanks

**Comment by AamirSohailKmAs** [comment]
This is related to another extension [intelephense](https://github.com/bmewburn/vscode-intelephense), this repo is for **Laraphense** extension.
